### ISSUE TITLE
Feature: Enforce hydro budgets over the non-lookahead timepoints of the horizon

### ISSUE THREAD

**Issue by sriharid** [blue-marble/gridpath#1139]
Hydro budgets are enforced over the entire horizon including the spinup/lookahead timepoints. This may result in mismatch between the budgets and actual generation over the non-spinup/lookahead timepoints. This can be fixed by adding additional constraints to enforce the budget over the non-spinup/lookahead timepoints as well.

**Comment by anamileva** [comment]
This can already be done starting with v2014.1.0 by creating a horizon for the spinup/lookahead timepoints.
