### ISSUE TITLE
Using GAMS-bundled solvers

### ISSUE THREAD

**Issue by milindsmart** [blue-marble/gridpath#764]
GAMS comes bundled with several solvers, e.g. CPLEX, which can only be invoked through GAMS itself.
Using GAMS bundled solvers with Pyomo involves invoking the GAMS executable and passing the solver name as an argument. A variety of arguments ("Option"s) can be passed to GAMS itself, and some of them can be passed to the bundled solver.

GridPath has some behaviours that currently prevent use of GAMS bundled solvers. These are explored below.

**Comment by anamileva** [comment]
@milindsmart, I'm doing some issue cleanup and don't know what to do with this one, as I don't have access to GAMS and can't work through the problem. If at some point you can document some of what you learned and perhaps add here from our discussion on Slack, I'd appreciate it.

**Comment by milindsmart** [comment]
Hi Ana, and sorry for the long delay, I was on a hiatus of sorts from GridPath due to some other projects. I'm definitely available now for some time.

With respect to this particular issue, I'll be happy to develop a PR since I have the GAMS instance to work with. Need your guidance on the best way to architect and modify this though. Let me know if this sounds okay to you. I'll also document this further (including Slack discussions) by tomorrow.

**Comment by milindsmart** [comment]
The secondary issue with using GAMS with GridPath is about getting parameters to GAMS and the solvers from the GridPath database. Before getting into it, I want to say that I'm not very happy about the aesthetics of the architecture involved in using GAMS with GridPath, seems like a lot of layering violations. It seems inevitable though with indirections like GP CSVs → GP database → GP tab files → Pyomo → GAMS → Bundled-solver... Let me explain

Currently solver_options are meant to pass options directly to the solver. The way this works is, first, a solver object is attempted to be instantiated from [`SolverFactory`](https://github.com/Pyomo/pyomo/blob/3058f462d8069901e6c04651ae5b962b60f45cb7/pyomo/opt/base/solvers.py#L138). The SolverFactory class uses the `solver_name` passed to it from GP and calls a specialised subclass such as  [GAMSSolver](https://github.com/Pyomo/pyomo/blob/3058f462d8069901e6c04651ae5b962b60f45cb7/pyomo/solvers/plugins/solvers/GAMS.py#L126) via a system of decorators and registration. 

For GAMS, there is a [choice of running GAMS](https://www.gams.com/blog/2020/06/new-and-improved-gams-links-for-pyomo-and-jump/) through the shell, or through a Python API. This functionality is accessed via a keyword argument to `SolverFactory`: 

https://github.com/Pyomo/pyomo/blob/3058f462d8069901e6c04651ae5b962b60f45cb7/pyomo/solvers/plugins/solvers/GAMS.py#L125-L135

GridPath currently does not pass any options to `SolverFactory`.

**Comment by milindsmart** [comment]
Another set of parameters that matter here are the [`GAMSSolver`-specific parameters fed to `solve()`](https://pyomo.readthedocs.io/en/stable/library_reference/solvers/gams.html) like `logfiles`, `load_solutions` and `tmpdir`. Thankfully, these are passed on properly as long as they are added to `solver_options`.

A third set of parameters - anything in `io_options` - will be passed on by GAMSSolver to GAMSWriter which writes out a GDX file that gets passed to GAMS itself. This [includes ](https://pyomo.readthedocs.io/en/stable/library_reference/solvers/gams.html#pyomo.repn.plugins.gams_writer.ProblemWriter_gams) `warmstart`, the all-important `solver` discussed in the first post, `skip_trivial_constraints`, and `mtype` (model type - lp/mip/?).  There too, we are mostly lucky since Pyomo passes any options that are not recognised by GAMSSolver into `io_options`, for GAMSWriter. One option however gives us issues - `add_options`.

**Comment by milindsmart** [comment]
`add_options` consists of ["option"s to be fed to GAMS](https://www.gams.com/34/docs/UG_OptionStatement.html) that are not recognised by Pyomo at all (neither by base Pyomo, nor by GAMSSolver, nor by GAMSWriter). GAMSWriter tries to use it as an list of strings (actually just an iterable of strings), adding them to the GMS file, which is then run by GAMS. A practical example of a parameter I needed to pass is `Option threads=4`, which GAMS uses to enable parallelism in the solver. 

This doesn't work with the `solver_options` framework in GridPath because any text in the value column is already implicitly a string, which does not allow itself to be considered as an iterable (except as a character-by-character iterable like any string).

**Comment by milindsmart** [comment]
Finally, some solver-specific parameters cannot be [set in any other way](https://www.gams.com/34/docs/UG_SolverUsage.html#BASIC_USAGE_SOLVER_OPTION_FILE) than having a separate `.opt` file in the GAMS working directory. A prominent example is the [lpmethod](https://www.gams.com/33/docs/S_CPLEX.html#CPLEXlpmethod) parameter used for choosing the barrier method. This cannot be set in any other way than a `cplex.opt` file, AFAIK.

**Comment by milindsmart** [comment]
To summarise, the following extensibility points are involved when trying to use GridPath with GAMS

| Extensibility point | Current status | Possible modification |
| --- | --- | --- |
| Solver name (= "gams") | Currently tied to the chosen `solver_options` value | Remove constraint |
| Pyomo-GAMS interface type (Shell/Python API) via `solver_io` argument to `SolverFactory` | No current way of doing this in GP | This functionality applies to solver( interface)s other than GAMS as well, so perhaps another column in `solver_options` (maybe called `solver_io`) is called for |
| GAMSSolver parameters | Works as intended | NA |
| GAMS parameters (via GAMSWriter) |   Also works since unrecognised options are passed properly to GAMSWriter (`solver` is currently tied to the solver name and `solver_options` value ; `add_options` doesn't work since current functionality doesn't allow it to be a string as required by GAMSWriter) | Remove constraint on `solver`. `add_options` can become a list if repeated multiple times with different values for the same key |
| Solver-specific parameters (in a `solvername.opt` text file) | No current way of doing this in GP | Custom python code or [some shell hack](https://stackoverflow.com/a/64698920/517835) |

But there's almost certainly a better way of doing this.

**Comment by anamileva** [comment]
Closed with #881.
