### ISSUE TITLE
KeyError not valid for indexed component 'TxNewLin_Build_MW' while exporting transmission results

### ISSUE THREAD

**Issue by Janie115** [blue-marble/gridpath#800]
Can be fixed by replacing "m.TX_OPR_PRDS" by "m.TX_NEW_LIN_VNTS" in "gridpath\transmission\capacity\capacity_types\tx_new_lin.py" line 341.

**Comment by ranjitster** [comment]
Thanks. We are aware of this issue. An additional error in writing the transmission_new_capacity result to the db.

**Comment by anamileva** [comment]
The issue raised by @Janie115 is now fixed on develop and the fix will be part of the next release. @ranjitster, could you elaborate on the additional error you are seeing?

**Comment by ranjitster** [comment]
@anamileva the results of new build transmission were not being written to the sql db. I have made the changes on my end but if you may have already included this in your refactoring.

**Comment by anamileva** [comment]
Closed via #803 with v0.10.0 release.
