### ISSUE TITLE
Type-in fields on settings page do not work

### ISSUE THREAD

**Issue by nmgeek** [blue-marble/gridpath#810]
For file paths, if you type in a setting value then type ENTER, the setting value is not set.  Instead, you have to open the Browse window and navigate to the path for the file and select it there.

This is cumbersome but not too bad, except ...

On Mac, for the solver, this makes it impossible to use the GUI to set the solver path.  This is because when you install cbc it is installed under /usr.  /usr is hidden in the file browser so you cannot navigate to the cbc executable in the browse window.

I suspect you can work around this by creating a symlink from your home directory.
Or you could work around it by typing the value directly into the settings file.   I have not yet found the location of the settings file.

**Comment by anamileva** [comment]
To show invisible directories on Mac, hold down the Command, Shift and Period keys: command + shift + [.]

**Comment by nmgeek** [comment]
Nice!  That worked.  

For the record you don't really "hold" those keys, just press those keys after the browse window is open and all the hidden dirs are added to the list.
