### ISSUE TITLE
Populate From Scenario not filling in inputs

### ISSUE THREAD

**Issue by cboettiger-factset** [blue-marble/gridpath#815]
I am using the UI and attempting to create new scenarios by auto-filling with an existing scenario. The scenario is based around the 2periods example. I have been able to populate the 2periods data into the DB and successfully run it. However, when I try to use it to create a new scenario with the populate button, it only fills in the optional features checkboxes and nothing else.

Thanks for any help.

**Comment by anamileva** [comment]
This should now be fixed if you upgrade to v0.10.1. Please reopen this issue if you are still running into the same problem.
