### ISSUE TITLE
Missing definition of 'year' horizon not caught during validation

### ISSUE THREAD

**Issue by nmgeek** [blue-marble/gridpath#819]
The documentation says 'year' is a valid balancing type.  But when running my scenario I get this error from the run.

I am building up from the published examples so running a scenario with only two days in two different years.  Perhaps I have to go to a full 365 day scenario before I can legally use a project with a balancing type of "year"?

Regardless it seems like this error should have been caught in the validation.  The validation report could then explain more clearly what I did wrong.

```
RuntimeError: Failed to set value for param=balancing_type_project, index=Pumped_Hydro_Storage, value=year.
	source error message=Invalid parameter value: balancing_type_project[Pumped_Hydro_Storage] = 'year', value type=<class 'str'>.
	Value not in parameter domain BLN_TYPES
```

**Comment by nmgeek** [comment]
It turns out that 'year' would be a 'horizon' (aka _balancing_type_horizon_) and _horizons_ with names like 'year' are not built in to gridpath.  You have to define the _horizons_ in the temporal subscenario.  The temporal subscenario called, _2horizons_1period_, provided in the examples, does define 'year' (the two horizons are 'day' and 'year').  I had been using the _1horizon_1period_ subscenario which defines only 'day'.

Regardless, shouldn't _gridpath_validate_ catch the inconsistency and provide a helpful error message so you don't get the cryptic message I got when running the scenario?

**Comment by anamileva** [comment]
Good work finding the problem with the inputs. That type of input error is indeed a good candidate for validation. We already have a list for validations to implement in #6 and I added this one there.
