### ISSUE TITLE
Add constraint to prevent simultaneous charge and discharge from a storage project

### ISSUE THREAD

**Issue by nmgeek** [blue-marble/gridpath#839]
I am modeling pumped hydro storage (PSH).  Some, if not all, PSH projects cannot charge and discharge simultaneously but GridPath allows this which leads to incorrect results.  

In my model there is a cost for curtailing variable generation.  The curtailment cost is more expensive than the cost to operate PSH discharge so it is cost-optimal to "dump" wind or solar energy by charging and discharging storage.  The energy is "dumped" in the efficiency loss of the PSH pumps and generators.  While this could possibly be a way to save excessive curtailment fees, it is not physically possible.  So I would like a constraint to prevent it.

We need the option to make charging and discharging exclusive.  I plan to tackle an enhancement and will post on my progress.

**Comment by anamileva** [comment]
That's a common problem. If you have an RPS constraint, you can make the storage projects contribute toward the RPS target, which will make storage losses count toward the target (change the `stor_losses_factor_in_energy_target` value if you want only a fraction of the losses to be accounted for). If you are only using a curtailment cost, I'd suggest summing up storage losses and multiplying those by the curtailment cost (and a param that determines how much of the storage losses to count similar to the behavior or `stor_losses_factor_in_energy_target`). Alternatively, you could implement a storage module with integer variables to force only charging or discharging, but that will have a cost for runtime.

**Comment by nmgeek** [comment]
I wasn't using an RPS target: my portfolio is 100% renewable.  I could probably set 100% as a target but the energy target subscenarios look kind of complicated.

Regarding curtailment cost, are you saying to add a storage-specific implementation of `curtailment_cost_rule` like below?  If I take this route then should I put into a "user customization module" somehow?

(I am not sure about how the efficiency should get applied.  Maybe it has already been accounted for in the charge/discharge MW. I will work through that.)

+def curtailment_cost_rule(mod, g, tmp):
+    """
+    Apply curtailment cost to round trip storage loss: to balance
+    against curtailment of variable projects.
+    """
+    return (mod.Stor_Discharge_MW[g, tmp] * (1. - mod.stor_discharging_efficiency[g]) +
+            mod.Stor_Charge_MW[g, tmp] * (1. - mod.stor_charging_efficiency[g])) \
+        * mod.curtailment_cost_per_pwh[g]

**Comment by anamileva** [comment]
Yes, this can be done simply by adding a `curtailment_cost_rule` to the `stor` operational type. GridPath will take care of the rest downstream. I think you should be multiplying `Stor_Discharge` by `(1-dicharging_efficiency)/discharging_efficiency`. We'd also need to multiply by a parameter similar to `stor_losses_factor_in_energy_target` that allows us to apply the curtailment cost to all, none, or some of the losses. The default value for that parameter should probably be 1.

**Comment by nmgeek** [comment]
PR submitted.  I didn't see any way the user can set `stor_losses_factor_in_energy_target` in the inputs so there is also no way to set the new parameter, `stor_losses_factor_curtailment`.

(It has been a while since I submitted a branch PR to another repo so let me know if I did not do it correctly.)

**Comment by anamileva** [comment]
Closed with v0.12.0 release.
