### ISSUE TITLE
Maintain highest SOC in storage project

### ISSUE THREAD

**Issue by nmgeek** [blue-marble/gridpath#849]
As best I can tell, there can be a set of equal-cost solutions for a storage project where the only difference is _when_ the project is charged sufficiently to meet the discharge requirements of the scenario.  In my experience, the (cbc) optimizer is always choosing the solution that waits until the last possible timepoint to ramp up the state of charge.  We could call this a "just in time" policy.

With my limited experience, I believe operators of storage prefer a solution which aggressively charges storage so as much energy as possible is available for any contingency.  You might call this a variable reserve.

Furthermore, for hydro storage, discharge is more efficient when the upper reservoir is maintained with a larger state of charge.  (This might be offset by less efficient charging, but you could argue it's best to prefer more efficient discharge because it maximizes the energy capacity of the project.)

I was able to get the aggressive charging behavior by modifying `variable_om_cost_rule` in _stor.py_ as shown here.  This subtracts a tiny cost which is a credit for maintaining the SOC at a higher value.

This solution is problematic because the denominator is an arbitrary number: I tried using the total storage capacity as the denominator but for "disabled' storage projects the value is zero and the optimizer crashes with a divide-by-zero.

Also, the cost delta is just a made up number.  Ideally it would correspond to some kind of credit for maintaining variable reserve.

```
<     return mod.Stor_Discharge_MW[g, tmp] * mod.variable_om_cost_per_mwh[g]
---
>     # discount cost by the fraction of full SOC, ie add tiny credit for higher SOC
>     return mod.Stor_Discharge_MW[g, tmp] \
>         * mod.variable_om_cost_per_mwh[g] \
>         - mod.Stor_Starting_Energy_in_Storage_MWh[g, tmp] \
>         / 1000000.

```

**Comment by anamileva** [comment]
I'd suggest handling this via a "tuning cost." There is a `tuning_cost_scenario_id` already that you can use for this purpose. You can follow the example of tuning done to avoid excessive ramping in degenerate problems.

**Comment by anamileva** [comment]
To me it makes more sense to apply the cost to (energy_capacity - starting_energy_in_storage), i.e. penalize whenever storage is not full.

**Comment by nmgeek** [comment]
Yes, your formula will work better: it allows a linear constraint without the arbitrary denominator.  I will look at the "tuning cost" approach.

**Comment by anamileva** [comment]
Great, let me know if you need more pointers.
