### ISSUE TITLE
Endogenous availability availability calculation should be weighted

### ISSUE THREAD

**Issue by PascalLesage** [blue-marble/gridpath#854]
In both the continuous and the binary availability types, the unavailability calculated in the availability constraints (respectively [AvlBin_Tot_Sched_Unavl_per_Prd_Constraint](https://github.com/blue-marble/gridpath/blob/c0ec4d2d93592f9514169ab5cca5a655170e94d1/gridpath/project/availability/availability_types/binary.py#L223) and [AvlCont_Tot_Sched_Unavl_per_Prd_Constraint](https://github.com/blue-marble/gridpath/blob/c0ec4d2d93592f9514169ab5cca5a655170e94d1/gridpath/project/availability/availability_types/continuous.py#L227)) should be weighted by the timepoint weight.

**Comment by anamileva** [comment]
Closed with v0.12.0 release.
