### ISSUE TITLE
Project Capacity Groups Min Build Requirements

### ISSUE THREAD

**Issue by jhimelic** [blue-marble/gridpath#876]
Issue: GridPath appears to return an infeasibility anytime I include a minimum build requirement at the capacity group level, regardless of the amount defined

steps taken: 
- verified that the assigned projects to the active capacity group are defined as gen_new_lin and have non-null values defined in the project_new_potential csv.
- scenario a) inserted very low min build requirements in the capacity_group_new_capacity_min column
- scenario b) inserted very low min build requirements in the capacity_group_total_capacity_min column
- scenario c) inserted very low min build requirements in both the capacity_group_new_capacity_min & capacity_group_total_capacity_min columns
- please note that the corresponding max build requirement values are greater than the defined minimums for all scenarios

Gridpath results:
- if i run a scenario where only the capacity group's max build requirements is active, the model will solve successfully.
- however, for all three scenarios outlined above, when i activate a min build requirement in the model the solver returns the following message in the run log:
"Presolve determined that the problem was infeasible with tolerance of 1e-08
Analysis indicates model infeasible or unbounded
1 infeasibilities
Analysis indicates model infeasible or unbounded"
it then goes to: "Perturbing problem by 0.001% of 53010.477 - largest nonzero change 0.053020466 ( 9.4969356%) - largest zero change 0.053020431..." and continues trying to solve the problem 
- after running for several hours the GUI will indicate the model successfully finished. however, the following is recorded in the log file: 

"Primal infeasible - objective value -1.2347641e+10
PrimalInfeasible objective -1.23476408e+10 - 1533568 iterations time 16176.922
Result - Linear relaxation infeasible"

Other:
- i am running version: 0.11.0 of GridPath
- i am using the coin-or CBC solver.

**Comment by anamileva** [comment]
I looked over the code for the capacity group functionality and did not find an obvious bug. There is also a working test example that includes both a min and max on new group capacity (2periods_new_build_capgroups) and does not result in an infeasibility. I have used the functionality before without encountering this problem, so I'm inclined to believe there's a data input issue, perhaps a conflict with another constraint, but I can't be certain without taking a closer look at the data inputs.

**Comment by jhimelic** [comment]
thanks ana. i will go back and check my setup again.

**Comment by jhimelic** [comment]
issues resolved.

i was able to flag down the issue and thought i would share my findings in the event other users encounter this problem. 

it turns out that the periods with defined min build requirements have to match the active temporal period for the study. 

for example, let's say you have defined min build requirements for a planning horizon that spans 2022-2035 but are only actively modeling a subset of that horizon (e.g., 2022) in your temporal subscenario id. the model will be flagged as infeasible if you define a non-null min build requirement for any period outside of the active modeling window (e.g. 2025). 

once i limited my min build requirement entries to match the active periods defined in temporal subscenario - in this case 2022 - the infeasibility issue was resolved. 

hope this helps. happy modeling
