### ISSUE TITLE
Equality in Meet_Fuel_Burn_Limit_Abs_Constraint

### ISSUE THREAD

**Issue by Janie115** [blue-marble/gridpath#896]
In PR  #880, the inequality sign (<=) was changed to equality sign (==) in constraint Meet_Fuel_Burn_Limit_Abs_Constraint. It should remain an inequality sign because this constraint was first developed to represent a maximum quantity of fuel to be burned in a fuel burn limit balancing area.

https://github.com/blue-marble/gridpath/blob/65dcb49384cf8024b23754217ab5a1743efad8fb/gridpath/system/policy/fuel_burn_limits/fuel_burn_limit_balance.py#L79

**Comment by anamileva** [comment]
Closed with v0.13.0 release.
