### ISSUE TITLE
Projects in project capacity group not in the project portfolio

### ISSUE THREAD

**Issue by Janie115** [blue-marble/gridpath#954]
Usually, when we would like to remove a project, we can just remove it from the portfolio and, when creating the scenario input, it will select only the relevant projects (only projects in portfolio) to create the different input files. However, it is not the case for project_capacity_groups. I got the following error while building the model:

ValueError: Cannot add value _project_name_ to Set PROJECTS_IN_CAPACITY_GROUP[_capacity_group_name_].
The value is not in the domain PROJECTS

**Comment by anamileva** [comment]
Closed with v0.15.0.
