### ISSUE TITLE
Error while getting inputs from database for ELCC surface 

### ISSUE THREAD

**Issue by Janie115** [blue-marble/gridpath#970]
IndexError: Replacement index 0 out of range for positional args tuple

It is not able to use the proper scenario id.

https://github.com/blue-marble/gridpath/blob/670a8560a004a831db5ce61e475c7217f235255f/gridpath/project/reliability/prm/elcc_surface.py#L264

**Comment by anamileva** [comment]
Closed with v0.15.0.
