### ISSUE TITLE
`solver_options.csv` is written with OS-determined line-endings, unlike all other scenario metadata CSVs

### ISSUE THREAD

**Issue by milindsmart** [blue-marble/gridpath#980]
`solver_options.csv` is written in `get_scenario_inputs.py` without specifying the `lineterminator` argument, unlike other CSV files written by functions in this python file, like  `scenario_description.csv`.

See `solver_options.csv` :
https://github.com/blue-marble/gridpath/blob/c32e0333811fe60e45822155641b103dd25cfe62/gridpath/get_scenario_inputs.py#L402

versus `scenario_description.csv` : 
https://github.com/blue-marble/gridpath/blob/c32e0333811fe60e45822155641b103dd25cfe62/gridpath/get_scenario_inputs.py#L352

`csv.writer` [defaults to](https://docs.python.org/3/library/csv.html#csv.Dialect.lineterminator) CRLF rather than LF. `newline=""` [passes newlines](https://docs.python.org/3/library/functions.html#open) untranslated.

The net effect of this is that running the `python -m unittest discover tests` causes `solver_options.csv` in `test_w_solver_options` to show up as modified according to Git. I suggest `solver_options.csv` can also use `LF` like everything else.

**Comment by anamileva** [comment]
Closed with v0.15.0.
